//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IdLibro { get; set; }
        public string NombreLibro { get; set; }
        public Nullable<int> IdAutor { get; set; }
        public Nullable<int> NumeroPaginas { get; set; }
        public string FechaPublicacion { get; set; }
        public Nullable<int> IdEditorial { get; set; }
        public string Edicion { get; set; }
        public Nullable<int> IdGenero { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
